[workspace]
members = ["./src/*", "./tasks/*"]
default-members = ["src/cli"]
resolver = "3"

[workspace.package]
authors = ["Leo Borai <estebanborai@gmail.com>"]
version = "0.0.0-pre.b2273df"
edition = "2024"
categories = ["web-programming"]
description = "🦀🧡🧉"
documentation = "https://docs.rs/mate"
keywords = ["job", "queue", "scheduler", "wasm"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/LeoBorai/mate"
readme = "./README.md"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
axum = "0.8"
bytes = "1.11"
clap = "4.5"
include_dir = "0.7"
log = "0.4"
proc-macro2 = "1.0"
reqwest = "0.13"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
tempfile = "3.24"
tokio = "1"
toml = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = "1.19"
wasmtime = "40"
wasmtime-wasi = "40"
wasmtime-wasi-http = "40"
wit-bindgen = "0.51"
wstd = "0.6"

mate-config = { path = "./src/config" }
mate-executor = { path = "./src/executor" }
mate-ipc = { path = "./src/ipc" }
mate = { path = "./src/mate" }
mate-repository = { path = "./src/repository" }
mate-task = { path = "./src/task" }
